var jsonData = [{
            "0": "Think about previous vehicles owned",
            "1": "Notice Mazda",
            "2": "Attend Event",
            "3": "See brand sponsorship / advertising",
            "4": "Interested in Mazda vehicles",
            "5": "Information Gathering",
            "6": "Decide to visit a dealer",
            "7": "Compare to competitors",
            "8": "Visit a dealer",
            "9": "Confirm model, trim and options",
            "10": "Purchase Vehicle",
            "11": "Look forward to delivery",
            "12": "Delivery",
            "13": "Welcome",
            "14": "Deepen bond with Mazda",
            "15": "Receive ongoing communications",
            "16": "Find out a service is required",
            "17": "Schedule the service",
            "18": "Go to service",
            "19": "Service car",
            "20": "Post service",
            "21": "Accidents",
            "22": "Malfunction",
            "23": "Recall",
            "24": "Re evaluate choices",
            "25": "Explore options as a Mazda owner",
            "26": "Re enter funnel (start at 1)",
            "27": "Recommit",
            "Keyword": "Touchpoint-Name"
        },
        {
            "0": "Stage 1",
            "1": "Stage 1",
            "2": "Stage 1",
            "3": "Stage 1",
            "4": "Stage 2 ",
            "5": "Stage 3 ",
            "6": "Stage 3 ",
            "7": "Stage 3 ",
            "8": "Stage 3 ",
            "9": "Stage 4",
            "10": "Stage 4",
            "11": "Stage 4",
            "12": "Stage 4",
            "13": "Stage 5",
            "14": "Stage 6",
            "15": "Stage 6",
            "16": "Stage 7",
            "17": "Stage 7",
            "18": "Stage 7",
            "19": "Stage 7",
            "20": "Stage 7",
            "21": "Stage 8",
            "22": "Stage 8",
            "23": "Stage 9",
            "24": "Stage 10",
            "25": "Stage 10",
            "26": "Stage 10",
            "27": "Stage 10",
            "Keyword": "Stage"
        },
        {
            "0": "Passive and Active Assimilation",
            "1": "Passive and Active Assimilation",
            "2": "Passive and Active Assimilation",
            "3": "Passive and Active Assimilation",
            "4": "Interested in Mazda Vehicles ",
            "5": "Research and Evaluation/Information Gathering",
            "6": "Research and Evaluation/Information Gathering",
            "7": "Research and Evaluation/Information Gathering",
            "8": "Research and Evaluation/Information Gathering",
            "9": "Purchase ",
            "10": "Purchase ",
            "11": "Purchase ",
            "12": "Purchase ",
            "13": "Welcome",
            "14": "Ongoing Use",
            "15": "Ongoing Use",
            "16": "Servicing and Repair",
            "17": "Servicing and Repair",
            "18": "Servicing and Repair",
            "19": "Servicing and Repair",
            "20": "Servicing and Repair",
            "21": "Support",
            "22": "Support",
            "23": "Concern",
            "24": "End of Life",
            "25": "End of Life",
            "26": "End of Life",
            "27": "End of Life",
            "Keyword": "Journey-Phase"
        },
        {
            "0": "N/A",
            "1": "Breakthrough",
            "2": "Breakthrough",
            "3": "Breakthrough",
            "4": "Intrigue",
            "5": "Inform",
            "6": "Empower",
            "7": "Empower",
            "8": "Celebrate",
            "9": "Celebrate",
            "10": "Celebrate",
            "11": "Celebrate",
            "12": "Celebrate",
            "13": "Welcome",
            "14": "Bond",
            "15": "Bond",
            "16": "Deliver",
            "17": "Deliver",
            "18": "Deliver",
            "19": "Deliver",
            "20": "Deliver",
            "21": "Support",
            "22": "Suport",
            "23": "Support",
            "24": "Reward",
            "25": "Reward",
            "26": "Reward",
            "27": "Reward",
            "Keyword": "Brand-Imperative"
        },
        {
            "0": "2.23",
            "1": "1.99",
            "2": "2.2",
            "3": "2.02",
            "4": "2.23",
            "5": "2.50",
            "6": "2.47",
            "7": "2.38",
            "8": "2.56",
            "9": "2.38",
            "10": "2.44",
            "11": "2.32",
            "12": "2.62",
            "13": "2.47",
            "14": "2.20",
            "15": "2.35",
            "16": "2.56",
            "17": "2.35",
            "18": "2.59",
            "19": "2.5",
            "20": "2.65",
            "21": "2.41",
            "22": "2.5",
            "23": "2.59",
            "24": "2.23",
            "25": "2.41",
            "26": "2.44",
            "27": "2.29",
            "Keyword": "Satisfaction-Level"
        },
        {
            "0": "1.00",
            "1": "2.16",
            "2": "1.00",
            "3": "2.3",
            "4": "1.00",
            "5": "1.27",
            "6": "1.61",
            "7": "1.75",
            "8": "2.23",
            "9": "1.00",
            "10": "2.5",
            "11": "2.5",
            "12": "1.41",
            "13": "2.43",
            "14": "1.00",
            "15": "1.00",
            "16": "1.95",
            "17": "1.00",
            "18": "1.95",
            "19": "4",
            "20": "2.23",
            "21": "1.61",
            "22": "1.2",
            "23": "1.34",
            "24": "1.00",
            "25": "1.68",
            "26": "1.00",
            "27": "1.00",
            "Keyword": "Importance"
        },
        {
            "0": "Talked to others I know who recently bought/leased a vehicle: 2.23",
            "1": "Noticed cars parked/on the road: 1.99\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "2": "Attend manufacturer event: 2.17\r\nAttend dealer event: 2.20",
            "3": "Saw ads that interested me: 2.02\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "4": "Looked into the history : 2.23\r\nResearchabout the corporate social responsibility initiatives: 2.17",
            "5": "Visited the dealership's website: 2.50\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "6": "Submitted a request to be contacted by a dealership: 2.47\r\nSpoke with the sale associate before visit to dealership: 2.35\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "7": "Configured a car on manufacturer's website: 2.38\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "8": "Visited a dealership: 2.53\r\nTook vehicle(s) for a test drive: 2.56\r\nDealership had treats/snacks at dealership: 2.14\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "9": "Negotiated price with dealership:2.38\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "10": "Got preapproved for an auto loan:2.35\r\nSpoke to dealership about financing/loan:2.35\r\nTraded in or sold old vehicle: 2.44\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "11": "Received a thank you note from the dealership/sales associate after visiting: 2.32\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "12": "Picked up vehicle at dealership: 2.62\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "13": "Downloaded the mobile owner’s app: 2.47\r\nVisited my owner portal online: 2.38\r\nReceived a welcome/on-boarding kit/package: 2.23\r\nPurchased accessories for vehicle: 2.47\r\nPosted photos of my new vehicle: 2.29\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "14": "Joined and used owner forums: 2.20\r\nAttended live events from the manufacturer: 2.05",
            "15": "Received e-mails from the manufacturer: 2.35\r\nReceived SMS/texts from the manufacturer: 2.30\r\nUsed the mobile owner’s app: 2.35\r\n",
            "16": "Received a reminder it was time for maintenance service: 2.56\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "17": "Call dealership: 2.35\r\nRessolve issues on website/app: 2.32\r\n",
            "18": "Went to the dealership for routine maintenance service: 2.59\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "19": "Dealership had treats/snacks at dealership: 2.41\r\nUsed a courtesy/loaner vehicle during service or repair: 2.50\r\nService center provided a video walkthrough of service done \r\non my vehicle: 2.41\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "20": "Took a survey from the manufacturer about my vehicle service: 2.44\r\nReceived coupons/vouchers from manufacturer or dealership: 2.35\r\nReceived a free/complimentary service, such as car wash or oil change: 2.65\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "21": "Used roadside assistance: 2.41\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "22": "Went to the dealership for service work on an issue with the vehicle: 2.50\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "23": "Received notification about a potential parts or vehicle recall: 2.59\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "24": "Talked to others I know who recently bought/leased a vehicle: 2.23",
            "25": "Received information about a new model of my vehicle: 2.41\r\nReceived information about the next year’s vehicle lineup: 2.38\r\n\r\n(1 -- \"Not At All Satisfied\";\r\n 2 -- \"Not Very Satisfied\";\r\n 3 -- \"Somewhat Satisfied\";\r\n 4 -- \"Very Satisfied\")",
            "26": "Visit manufaturer's social page: 2.29\r\nVisit manufacturer's website: 2.44",
            "27": "Dealership revisit for new model: 2.29",
            "Keyword": "Satisfaction-Level-Tooltip"
        },
        {
            "0": "Talked to others I know who recently bought/leased a vehicle: 1.00",
            "1": "Notice on the road: 2.16\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "2": "Attend manufacturer event: 1.00\r\nAttend dealer event: 1.00",
            "3": "Saw ads: 2.30\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "4": "Looked into the history : 1.00\r\nResearchabout the corporate social responsibility initiatives: 1.00",
            "5": "Visited the dealership's website: 1.27\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "6": "\r\nSubmitted a request to be contacted by a dealership: 1.20\r\nSpoke with the sale associate before visit to dealership: 1.61\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "7": "Configured a car on manufacturer’s website: 1.75\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "8": "Visited a dealership: 1.27\r\nTook vehicle(s) for a test drive: 1.89\r\nDealership had treats/snacks at dealership: 2.23\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "9": "Negotiated price with dealership: 1.00\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "10": "Got preapproved for an auto loan: 2.50\r\nSpoke to dealership about financing/loan: 1.55\r\nTraded in or sold old vehicle: 1.07\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "11": "Received a thank you note from the dealership/sales associate after visiting: 2.50\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "12": "Picked up vehicle at dealership: 1.41\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "13": "Downloaded the mobile owner’s app: 1.27\r\nVisited my owner portal online: 1.61\r\nReceived a welcome/on-boarding kit/package: 2.36\r\nPurchased accessories for vehicle: 1.75\r\nPosted photos of my new vehicle: 2.43\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "14": "Joined and used owner forums: 1.00\r\nAttended live events from the manufacturer: 1.00",
            "15": "Received e-mails from the manufacturer: 1.00\r\nReceived SMS/texts from the manufacturer: 1.00\r\nUsed the mobile owner’s app: 1.00\r\n",
            "16": "Received a reminder it was time for maintenance service: 1.95\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "17": "Call dealership: 1.00\r\nRessolve issues on website/app: 1.00\r\n",
            "18": "Went to the dealership for routine maintenance service: 1.95\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "19": "Dealership had treats/snacks at dealership: 2.50\r\nUsed a courtesy/loaner vehicle during service or repair: 3.11\r\nService center provided a video walkthrough of service \r\ndone on my vehicle: 4.00\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "20": "Took a survey from the manufacturer about my vehicle service: 1.68\r\nReceived coupons/vouchers from manufacturer or dealership: 2.23\r\nReceived a free/complimentary service, such as car wash or oil change: 2.09\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "21": "Used roadside assistance: 1.61\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "22": "Went to the dealership for service work on an issue with the vehicle: 1.20\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "23": "Received notification about a potential parts or vehicle recall: 1.34\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "24": "Talked to others I know who recently bought/leased a vehicle: 1.00\r\n\r\n\r\n",
            "25": "Received information about a new model of my vehicle: 1.61\r\nReceived information about the next year’s vehicle lineup: 1.68\r\n\r\nScale: 1 (\"Least Important\") - 4 (\"Most Important\")",
            "26": "\r\n\r\nVisit manufaturer's social page : 1.00\r\nVisit manufacturer's website: 1.00\r\n\r\n",
            "27": "\r\nDealership revisit for new model : 1.00\r\n\r\n",
            "Keyword": "Importance-Tooltip"
        },
        {
            "0": "Speaking to friends and family, Thinking about past experiences, Doing calculations to work out cost of ownership, etc.",
            "1": "See advertisement, See car on road, Rent a hire car, Ride in friends car.",
            "2": "Attend manufacturer event, Attend dealer event",
            "3": "Watching sport, Watching esport, Watching Youtube, Watching TV, Social media, Reading a magazine, Reading news online.",
            "4": "Look up what Mazda stands for, Research CSR initiatives",
            "5": "3rd party research, Solicit peer reviews, Visit MUSA, View product videos, Request Brochure, Questions in forum or social",
            "6": "Submit lead information, Visit dealer website, Brochure request, Youtube videos for Mazda.",
            "7": "Envision Mazda ownership, Configure Mazda model",
            "8": "Greeted at dealership, Do test drive, Learn about vehicle features",
            "9": "Choose options, Negotiate price",
            "10": "Discuss financing options, Discuss trade in options, Fill and sign paperwork",
            "11": "Receive a thank you note from dealer, Receive financial information, Plan what to do with the car when it arrives",
            "12": "Pick up vehicle from dealership, Have vehicle delivered, Go for first drive",
            "13": "Download Mazda app, First drive experiences, Share my new car purchase, Receive welcome kit, Research accessories, Pay first bill, UMX product walkaround",
            "14": "Get to know my car, Engage in owner forums, Attend mazda events, Take advantage of offers only Mazda offers, Introducing Mazda to family and friends",
            "15": "Receive emails about my car, Receive Mymazda push notification",
            "16": "Receive email, Notified through app, Notified through direct mail, See engine light in car, Look through service log to see when the last service was",
            "17": "Call the dealership, Use the MyMazda app to schedule an oppointment, Use the website to schedule an appointment",
            "18": "Drive to dealership, Drop vehicle off at dealership",
            "19": "Wait for car to be serviced, Get loaner car to take home, Receive video updates during service",
            "20": "Collect vehicle, Inspect vehicle, Notified of cost, Do paperwork/payment, Receive survey",
            "21": "Has an accident or vehicle is damaged, Use roadside assistance, Call insurance provider, Book/request an appointment for service or repair",
            "22": "Call the dealership, Search online for similar issues, Schedule appointment at the dealership",
            "23": "Read about potential recall, Notified of recall, Contact OEM, Schedule recall repair",
            "24": "Ask friends and family about vehicles, Think about value and reliability of current vehicle, Think about needs",
            "25": "Receive email, Receive direct mail, See add online or social media",
            "26": "Reconnecting with previous dealer, Searching for cars that suit my needs, Re-assessing how affordable my last vehicle was against my expectations",
            "27": "Discuss financing options, Discuss trade in options, Fill and sign paperwork",
            "Keyword": "Doing"
        },
        {
            "0": "Marketing",
            "1": "Marketing",
            "2": "Marketing",
            "3": "Marketing",
            "4": "Marketing",
            "5": "Marketing",
            "6": "Marketing",
            "7": "Sales",
            "8": "Sales",
            "9": "Sales",
            "10": "Sales",
            "11": "Sales",
            "12": "Sales",
            "13": "Sales",
            "14": "Engagement",
            "15": "Engagement",
            "16": "Service",
            "17": "Service",
            "18": "Service",
            "19": "Service",
            "20": "Service",
            "21": "Service",
            "22": "Service",
            "23": "Service",
            "24": "Marketing",
            "25": "Marketing",
            "26": "Sales",
            "27": "Sales",
            "Keyword": "Team"
        },
        {
            "0": "N/A",
            "1": "Active Awareness",
            "2": "Active Awareness",
            "3": "Active Awareness",
            "4": "Active Awareness",
            "5": "Research, Evaluation, Shopping",
            "6": "Research, Evaluation, Shopping",
            "7": "Research, Evaluation, Shopping",
            "8": "Sales",
            "9": "Sales",
            "10": "Sales / welcome",
            "11": "Welcome",
            "12": "Welcome",
            "13": "Welcome",
            "14": "Vehicle Education",
            "15": "Ownership",
            "16": "Intro to Service",
            "17": "First Maintenance / Continued Maintenance",
            "18": "First Maintenance / Continued Maintenance",
            "19": "First Maintenance / Continued Maintenance",
            "20": "First Maintenance / Continued Maintenance",
            "21": "Support",
            "22": "Support",
            "23": "Repair / Recall",
            "24": "IMOR",
            "25": "IMOR",
            "26": "IMOR",
            "27": "IMOR",
            "Keyword": "Tier1-Tier3-Use-Case"
        },
        {
            "4": "Free oil changes for healthcare workers and their families.",
            "10": "Roadster: Digital Retailing",
            "13": "UMX walkaround",
            "19": "Video walkthrough of service",
            "Keyword": "Existing-Work"
        },
        {
            "0": "Repurchase consideration centers mostly on the four pillars of loyalty: Trust, transparency, understanding and reliability",
            "1": "Independent achievers are more receptive to noticing cars on the road but Mazdas can be few and far between",
            "2": "Events appeal to a small audience of mostly premium car owners",
            "3": "Mazda customers are unique ",
            "4": "IAs are interested in the story of the car as well as the brand",
            "5": "There are things (tips and tricks) to buying cars that customers build into their research process",
            "6": "Getting pre-approved on a lean is a key factor in providing a great experience",
            "7": "Premium vehicle owners are more likely to come to the dealership knowing what they want and having had spoken to a dealer already",
            "8": "Customers value the role dealers play in helping them learn the features of the vehicle but are struggling to learn with socially distanced test drives",
            "9": "Premium owners and IAs like to know what trim and packages they want before entering the dealership.",
            "10": "Need to soften the experience gap between test drive and financial discussion",
            "11": "Deepen bond with the brand while customers are in the headspace.",
            "12": "Create shareable moments of new vehicle during onboarding ",
            "13": "Realizing the value of the vehicle shouldn't be left to chance ",
            "14": "Customers are comparing the app to other products they are using… and it is falling short",
            "15": "All customers remember are the coupons",
            "16": "Service affordability is more important than ever",
            "17": "Customers don't want to hand over the keys to their car even if it is more conveniant for them to do so",
            "18": "Customers are on high alert when at service centers",
            "19": "Understanding an individuals needs makes a huge difference",
            "20": "Every interaction is an opportunity to make customers feel valued",
            "22": "Some things are just part of owning a vehicle",
            "23": "Customers do not reward you when you do what they expect you to do - but they punish you when you slip up",
            "24": "Customers struggle with the idea of auto brand loyalty",
            "25": "Build relevance where and when it matters",
            "Keyword": "Research-Findings1-Header"
        },
        {
            "0": "Customers want what is convenient for them because at the end of the day they are buying something to make their lives better and easier. They are quick to trust but slow to forgive and forget.",
            "1": "Having a smaller share of the market and being outspent and outshouted means customers have fewer opportunities to be exposed to the brand.",
            "2": "Most car buyers aren't attending events. If they are, it's most likely to be a premium car owners and not mass-market. Dealer events were attended more then manufacturers.\r\n\r\nNote: Incidence for events in our research was very low.",
            "3": "For Mazda owners, the decision to buy a car showed traits of both premium and mass-market customers. Functional factors were important as well as how the car makes them feel. This may due to Mazda's transition from mass-market to premium and owners being split between mass-market and premium.",
            "4": "Few customers seek out OEM CSR initiatives (Subaru owners are an exception). Well placed CSR information can sway drivers (see Everlane transparent pricing)\r\n\r\nThere is an opportunity to lean into 'Japanese Craftsmanship' as a competitor to ’German engineering’. Existing Mazda owners love the vehicle aesthetic and Kodo design language.",
            "5": "Often these are deduced from research across a range of sources. What if these were aggregated and provided back to customers to help them buy Mazdas.",
            "6": "Getting pre-approved removes stress from the experience as customers can openly discuss options with confidence. Getting pre-approved speeds up the financial discussions and softens the experience gap between the test drive (which is valued) and the financial conversations (which are not).",
            "7": "Premium buyers are doing more and experiencing more touchpoints nefore visiting a dealer. Customers leasing vehicles show greater intent with -86% (across brands) leasing the vehicle they planned to when walking into the dealership vs. ~74% for purchasing.",
            "8": "Almost every customer recalled that they learnt about the features of the vehicle while at the dealership. This allows them to weigh up the pros and cons of vehicle options. This especially extends to test drives where customers normally rely on dealers to show them features of the car in context. Not having sales staff in the vehicle means customers left to their own devices to explore the features of the car while driving which is both not ideal nor safe.",
            "9": "Mass market customers are more likely to make last minute purchase decisions (trim, package etc.) in the dealership. This allows them to create a connection with the salesperson and negotiate a better deal for themself. They do not feel so strongly about the exact look of their car. They are opportunistic. This is different for premium mass-market customers who are guided heavily by their digital experience.",
            "10": "Customers enjoy dealings with dealers and test driving the vehicle but the experience takes a sharp turn when they begin financial discussions. Encouraging pre-approval may help remedy this and provide an experience that customers remember.",
            "11": "Just after purchasing a vehicle customers are more receptive to brand messaging. Having been down in the detail selecting the right vehicle now is the time to show them what it is like to be a Mazda owner.",
            "12": "Create uniquely Mazda experiences that bring Omotenashi principles to life.",
            "13": "Although dealers often doing a good job and selling the features of the car in the dealership customers are prone to forgetting or missing specific details. Ensuring a user has full and complete control/knowledge of their vehicle should not be left to chance. Building in regular check ins with customers to ensure they don't have outstanding questions can help Mazda build a relationship with customers and ensure customers get the most out of their vehicle.",
            "14": "Across all brands, car owners are least satisfied with the app and owner portal experience. Having very high expectations of mobile apps customers won't give the MyMazda product too many options before they disregard it and revert to more expensive, higher touch channels.\r\n\r\n",
            "15": "Few customers could recall any communications other than resale or service coupons.",
            "16": "Vehicle reliability is critical to brand loyalty and repeat purchases. By creating incentives that allow current vehicle owners to maintain their vehicle at a price within their budget, vehicle reliability is ensured. And in turn, these consumers should have a more favorable perception of their car’s brand which will be necessary when it comes time to purchase their next vehicle.\r\n- Mintel: Car Purchasing Process: Incl Impact Of COVID-19 US, July 2020.",
            "17": "Although there's growing appeal in the idea of pickup and delivery service options many customers are not ready to partake in the service themselves. Interviews uncovered some serious trust issues (handing over control of ones vehicle ot someone else ) that need to be considered before undertaking in initiatives in this space. \r\n\r\nGeneral appeal of contactless vehicle servicing is high, but the low proportion that say it's \"very appealing\" likely resembles how many would not use the service themselves.\r\n\r\n33% of Mazda owners find contactless vehicle servicing \"very appealing\". 77% consider it very/somewhat appealing\r\n\r\nMass Market Competitors find it slightly less appealing: 29% very appealing; 73% very/somewhat\r\nwhile Premium Competitors find it slightly more appealing: 35% very appealing; 82% very/somewhat\r\n\r\nIndepdent Achievers find it the most appealing: 48% very appealing; 87% very/somewhat",
            "18": "Show you are going above and beyond. Allow them to do everything on their own device rather than having to use a communal device.",
            "19": "Customers value understanding (one of the four pillars of loyalty). Whether is be providing a loaner car or making sure there is a safe place for them to wait while their car is services is essential in building trust. Building in flexibility and providing options during a vehicle service shows that you care and that you are trying to get the best outcome for the customer.",
            "20": "When collecting the vehcile, the thing that makes customers the happiest is being walked to their vehicle yet only 23% of Mazda customers experience this.",
            "22": "Customers understand that things go wrong and although frustrating, if responded to in a manner by which customers find acceptable they will often forgive and forget.",
            "23": "For the most part, customers have very basic expectations of an OEM. They will provide a high quality vehicle and they will support them when things go wrong. When extras are provided to customers that make them feel good favor is won, but when the OEM is not there to perform their most basic duty, everything else is forgotten.",
            "24": "When it comes to the idea of being loyal to one automaker and only purchasing vehicles from that brand, consumers are split almost equally across the board with roughly 30% agreeing, disagreeing and not being sure where they stand on the topic.\r\n\r\nLoyalty is a fairly abstract concept – while there are some logical facets to it, loyalty is heavily driven by emotion. There will always be a better deal, a better product, a better price – loyalty is what prevents the consumers from taking the other option and sticking with what they already have. \r\n- Mintel: Creating Loyalty In Automotive. January 2020.",
            "25": "Customers can be easily swayed from their decisions. Research shows that simply giving the shopper the option to choose their second choice brand was enough to entice 30% away from their initial choice.",
            "Keyword": "Research-Findings1-Body"
        },
        {
            "0": "Triggers for going in market changes for mass market and premium customers",
            "1": "Engage customers when you have a natural opportunity to form a bond",
            "3": "Mazda owners are more involved in the process",
            "4": "Pricing transparency can differentiate Mazda from other OEMs",
            "5": "Car enthusiasts will find the car they want and then find a way to make it work",
            "6": "Customers are made to do the hard work by shopping around for dealers and deals",
            "8": "Customers have a better experience when they have pre-approval before visiting a dealership",
            "10": "Lower end mass market customers don't want the bells and whistles. ",
            "11": "Welcome information is being lost among other email communications.",
            "12": "Customers who drive out with a vehicle need to get insurance before they can leave the dealership",
            "13": "Deepen bond with the brand while customers are in the headspace",
            "14": "Low end premium are increasingly buying high end mass-market",
            "15": "Customers switch off when they are sent redundant emails",
            "16": "Customers get anxious thinking about servicing and often shop around to try get a better deal",
            "17": "There is an opportunity to expand online offerings and presence for vehicle repair and maintenance",
            "18": "Dealerships use Mazda vehicles are a training ground",
            "19": "Transparent servicing is working",
            "20": "Small bonuses go a long way (It's the thought that counts)",
            "23": "A little love at the moments that matter can yield big results",
            "24": "Reliability sets the foundation for repeat brand purchases",
            "25": "Customers are more mindful of where they spend their money - Mazda is in a unique opportunity to benefit from more mindful and conservative shoppers.",
            "Keyword": "Research-Findings2-Header"
        },
        {
            "0": "Mass market customers are triggered by functional or situational needs. Premium owners may be triggered by emotional cues such as ones deire to validate sense of self or because having a luxury car is a status symbol.",
            "1": "When travelling customers are now more likely now than ever before to rent a vehicle. Public transport usage is down and although car rental companies saw a reduction in usage during the peak of the pandemic, the New Normal is likely to see an increase in rental car usage as domestic travel increases.\r\n\r\nCreate opportunities to get prospects and existing customers behind the wheel so they can experience different vehicles in the line up first hand.",
            "3": "They notice cars on the road more and they are more involved in information gathering. This could be attributed to the split between IA and mass-market customers who will both do extensive research to ensure they satisfy their individual needs.\r\n\r\nMazda owners stand out from other mass market car owners for noticing Mazda ads or cars parked/on the streeet prior to purchase (40% Mazda vs. 31% Mass Market Competitive)",
            "4": "Pricing transparency will capture the attention of some drivers who are not comlpetely price oriented and who are more commited to spending money with companies that align with their values (IAs).",
            "5": "In opposition to this, true mass-market customers start with a budget in mind and then look for the vehicle which has the best features that solve for their needs within their price range. Mass market customers are looking to satisfy functional needs like safety, price, etc. while Premium owners are looking to realize higher order needs like prestige, accomplishment and belonging. ",
            "6": "Shopping around' for dealers is a pain point for many customers. Customers try form strong bonds with trusted dealers to reduce the amount of effort the next time they look for a vehicle.\r\n\r\nInformation is spread across many different places and even when one finds a dealer with the vehicle they want, they have to find one that will accept the deal they're expecting to get.",
            "8": "Although already an option in the experience, only 50% of IAs who spoke to dealerships about financing or loans are actually doing pre-approvals. Research indicates that this is the most important thing to do to improve the purchase experience. Heavily encourage customers to do a pre-approval and assist them to do so when scheduling an appointment with a dealership.",
            "10": "They are solely price oriented. There may be opportunities to make them understand omotenashi but not at the expensive of the cost of their vehicle. They are determined with a single focus on getting the deal they want/need. There is little need to invest into their experience as they are not the target customer nor do they value a premium experience.",
            "11": "Use high priority channels (e.g. text) to welcome customers to the brand. Emails are getting lost with information coming from the bank, the dealership and the manufacturer.",
            "12": "Handing the experience to third parties means customers have to step away from the Mazda experience. How might we support drivers to navigate third parties (E.g. Insurers) in a way that maintains the Mazda way?",
            "13": "Once a customer has bought we do not go back to exposing them to the brand and the Mazda story. They are now primed to be receive and accept information about the vehicle and brand yet we wait until they are in the market again to re engage properly. ",
            "14": "Recent socio-political events have made customer more conservatice in their spending and will result in more low end luxury owners come to high end mass market. With these customeres come raised expectations for what experiences manufactureres should be delviering to customers.",
            "15": "Customers continue to receive communications from other dealerships well into ownership. This redundant information makes them 'switch off' to comms that come through.",
            "16": "Very price sensitive customers will shy away from using the manufacturer service center even though they know it is better for them to do so. Customers who are more forward thinking  recognize they they would rather spend a bit more for the peace of mind are more likely to go to the dealer. ",
            "17": "1/3 of Mazda customers new schedule appointments online, more than 2x competitors. CSI is highest when scheduling appointments over the internet/application.\r\n\r\nThe top reasons for not scheduling online were, wanted to speak to somebody before scheduling (36%) and lack of awareness (29%)\r\n\r\n- J.D. Power: 2020 US Customer Service Index (CSI) Study​.",
            "18": "Invest in increasing service retention and dealers will have more incentive to sell more Mazdas, use better dealers to do so and provide a better overall experience to customers.",
            "19": "Receiving a progress update during car service receives high satisfication among mass market owners.",
            "20": "Free oil changes, free batteries, all the small things that may not cost too much mean a lot to customers.\r\nMazda owners and other mass market owners are more satisfied with a free complimentart service (oil change or car wash) than other \"special moments\" such as name being on welcome sign, treats/snacks at dealership and coupon/vouchers.",
            "23": "Customers have few expectations from an OEM. Hoever, one of the key expectations is that when something goes wrong they will be their to support the customer and back their product. All the pillars of loyalty come to the fore during a recall experience (Trust, Transparecny, Understanding and Reliability). If an OEM does not take care of customers in the one instance they are expected to show up then customers will break any sense of loyalty and you'll find yourself in a feature battle with every other manufacturer.",
            "24": "Automakers have long been touting their low-mileage leases, $0 down payments and quick and easy financing. This is largely in part because price has been a primary driver behind consumer purchases. But when it comes to purchasing their next vehicle, 77% of consumers cited reliability over price as to why they repurchased from the same auto brand. This means that automakers will need to work with their Tier 3 counterparts to get a gauge on how reliable current vehicle owners perceive their car to be, as this will be an indicator of a repeat purchase. \r\n\r\n\"If a consumer feels that they can’t trust an automaker to produce reliable vehicles, then the odds of them repurchasing from that brand are slim.\" \r\n- Mintel: Creating Loyalty In Automotive. January 2020.",
            "25": "As a result of recentand upcoming socio-political events customers are moremindful of where they sepnd their money. 40% of US shoppers say they are more mindful of where they spend their money and 31% of shoppers say they are changing to less expensive products to save money. \r\n",
            "Keyword": "Research-Findings2-Body"
        },
        {
            "5": "The decision to buy is so serious because there is no return policy",
            "10": "Create a bespoke connection with the shopper in a way that brings Omotenashi principles to life ",
            "13": "Mass market owners disengage after purchase",
            "14": "Customers prefer forums and private channels/hashtags when engaging with a brand online/on social",
            "15": "Customers have relationships with dealers not the OEM",
            "17": "Customers have to wait too long between scheduling and appointment",
            "20": "Independent Achievers like being asked for input",
            "23": "Acquiring a new customer can cost five times more than retaining an existing customer.",
            "24": "At this stage customers have their own opinions ",
            "25": "Improve existing owner engagement at end of life/lease term",
            "Keyword": "Research-Findings3-Header"
        },
        {
            "5": "Ford Motor Co. introduced a on year return policy during COVID-19 for customers fell on hard times.\r\n\r\n\"A car is much more expensive and they don't have return policy. They don't have a use it for two weeks and return for full refund.I might consider it if there was refund option.\"",
            "10": "Improve lead conversion by adding additional moments of connection, delivered seamlessly through mobile (e.g. through SMS but then clicks through to a personalized microsite).  \r\n18% engaged with this touchpoint during most recent car purchase, indicating room to improve.",
            "13": "Mass market owners don't seem to not want to continue a relationship with the brand.\r\n\r\nPurchase car accessories (20%), post photos (18%), downloading the owners app (15%), receive welcome/on-boarding kit (13%).",
            "14": "Most customers don't have a strong enough bond/relationship with the brand that would encourage them to follow the brand on social media.  Most owners don't follow the brand they own except for Audi (48%), BMW (38%) and Acura (22%). Mazda, Honda, Toyota and VW have a similar number of owners following them (~11-13%).",
            "15": "Customers see the dealer and service center as providing ongoing customer service on the vehicle. This results in 1. the relationship being held more with the dealer then the brand. and 2. a strong bond forming between that dealer and customers. This impacts what customers expect from OEMs who are perceived as being there primarily to support customrs when things go wrong. See 19.recall for more information.",
            "17": "Customers wait an average of 4.23 days between scheduling and the actual appoinment. This is one of the longest wait times in the industry. The longer customers way, the less satisfied they are.\r\n- J.D. Power: 2020 US Customer Service Index (CSI) Study​.",
            "20": "IA's notice receiving surveys more than other customers. They have specific ideas about what types of experiences they want to receive and will help you bring improve if given the chance.",
            "23": "Increasing customer retention by 5% can increase profits from 25-95%. The success rate of selling to a customer you already have is 60-70%, while the success rate of selling to a new customer is 5-20%\r\n- HBR: The Value Of Keeping The Right Customers, Oct 2014",
            "24": "This touchpoint has low importance to driving purchase (or in this instance repeat purchase) as customers have already formed their own opinions on the brand and talking to others who have recently purchased will now change their mind. The size and importance of a vehicle purchase means when trust is formed it is stronger than the relationship felt toward other brands (e.g. clothing) but when it is broken, we see an equal yet opposite reaction.",
            "25": "Very few customers (IA, Premium or Mass market) recall receving new model or lineup information. Little engagement throughout the usage and into end of life phases mean customers go back to the drawing board, review their situational needs and compare against the competitive set every time they are considering a new vehicle.",
            "Keyword": "Research-Findings3-Body"
        },
        {
            "14": "Lack of awareness of the app and lack of useful features are preventing Mazda's App adoption and retention. ",
            "Keyword": "Research-Findings4-Header"
        },
        {
            "Keyword": "Research-Findings4-Body"
        },
        {
            "1": "Independent Achievers are looking for inspiration",
            "Keyword": "Supporting-Data-Header"
        },
        {
            "1": "Independant Achievers are more likely to have noticed the vehicle they purhcased on the road before starting to look for a new vehicle.\r\n\r\nIndependent Achiever = 34%\r\nMazda Owners (total) - 29%\r\nPremium Owners = 28%\r\nMass-Market Owners = 21%",
            "4": "Most likely to be done by premium owners (20%) and Subaru owners (21%)\r\n\r\nIAs are more likely to support brands that sponsor events or causes that they care about (IA=74% vs. General population=58%)\r\n- Kantar Experiential Research",
            "5": "Mazda owners are more engaged during the information gathering stage than other mass market owners. Mazda owners are most likely to be visiting vehicle review sites (42%) and the manufacturer webiste (42%). This is higher than any other competitor. They're also searching for incentives/deals (27%) and visiting 3rd price comparison sites (24%).",
            "6": "During this stage, Mazda and competitor owners are most likely to visit the dealer website (Mazda 51%). \r\n\r\nVery few, across all brands, request a brochure (5% for Mazda). \r\n\r\nThere is some vetting happening before they go to the dealership - 19% of Mazda owners talk to a dealer associate before visiting dealership. This is more in line with premium owners and Subaru and VW (~22-28%).\r\n\r\nPremium owners and Mazda owners are more likely than mass market owners to watch videos on the make/model and reviews on YouTube. Premium owners are especially satisfied with this experience",
            "7": "The online/digital experience and research phase plays a big role in decision making before consumers enter the dealership. IAs are the most mikely to do most to all of their reserach online: most/all shopping/research done before dealership, that's 53% for Premium and 58% for IA.\r\n\r\nAbout one-quarter of Mazda owners, along with premium owners, are configuring a car on the website, which is significantly higher than Honda and Toyota owners (both 15%). IAs and preium owners are more satisfied with the build and price tool. 70% of IAs said they were very satisifed compared to 66% of premium (vs. 54% among Mass Market competitors).\r\n\r\n51% of Mazda owners did most/all of the shopping/ research/decision making was done online before going to the dealership. This is just as high or higher for Premium and less so among Honda, Toyota and VW.",
            "8": "50% of Independent Achievers who speak to dealers about financing are not getting pre-approved for a loan.\r\n\r\nPremium brand owners are going to more dealerships when looking for vehicle (36% going to 3 or more vs. 26% of mass market owners)\r\n\r\nMass market are going to 1-2 dealerships, with Toyota owners most likely to only go to 1 dealership (52% of Toyota owners went to 1 dealership) and Mazda owners least likely to only go to 1 dealership (38% Mazda owners went to 1 dealership, 33% went to 2, 29% went to 3 or more)\r\n\r\nMazda owners have the lowest satisfaction with their dealership visit (52% very satisfied) compared to mass and premium competitors. Very Satsified: 80% of Audi owners , 64% of Subaru owners, 58% BMW, 57% VW.\r\n\r\nTest drive has the highest satisfaction across all touchpoints/stages among Mazda owners (76% very satisfied with test drive) and falls in the middle of competitors' satisfaction. But satisfaction plunges when it comes time to negoiated the price (only 33% mazda owners are very satisfied - the lowest of any brand)",
            "9": "Although not the majority, some consumers are making more specific decisions, such as trim, package and accessories, when in the dealership:\r\n\r\n38% of existing Mazda owners decided trim/package/accessories at dealer\r\n36% Mass competitors\r\n29% Premium competitor owners\r\n60% of Audi and BMW owners",
            "13": "Across all brands, car owners are least satisfied with the app and owner portal experience.\r\n\r\nWhen customers do post photos, they are very satisfied with the experience.\r\n \r\nOther top experiences during the honeymoon stage are purchasing accessories, receiving a welcome kit and receiving a personalized package/gift.",
            "14": "App store views = 2.5/5 starts and 2.8/5 stars on iTunes App Store and Google store respectively.\r\n\r\nTop reasons for never downloading the Mazda Owner's App:\r\n- 44% didn’t know there was an owners app\r\n- 24% don’t think it offers anything they need/want\r\n- 21% not familiar with the app’s feature/what it offers\r\n\r\nTop reasons for no longer using the Mazda Owner's app:\r\n- 44% only downloaded it for when they first purchased the vehicle\r\n- 20% didn’t have features they were using \r\n- 17% It had too match glitches/would crash\r\n- 14% I couldn't figure out how to use it",
            "15": "Across all brands, satisfication with emails from dealership and manufacturer is lower than several other touchpoints:\r\nThe top touchpoint experienced/recalled is emails from the manufacturer or dealer (more received emails from dealer). Although low, Mazda and BMW owners are the most likely to have received personalized mail (16%, 15%).",
            "16": "Mazda owners are less satsified than competitors on the reminder for maintenance service:\r\n- Mazda: 52% \r\n- Toyota: 70%\r\n- Total Mass Market Competitors: 64%\r\n- Total Premium Competitors: 66%",
            "17": "Mazda is -2.60 points Vs. Competititive set for ease of scheduling service visit. Mazda is also -0.14 points from 2019.\r\n- J.D. Power: 2020 US Customer Service Index (CSI) Study​.",
            "18": "Less than half of all brand owners have had their vehicle maintenanced at the dealership. Create \"special moments\" to get them in the dealership and for while they're there",
            "19": "The two biggest YOY increases in the J.D. Power CSI report:\r\nThoroughness of maintenance/repair work performed (+2.18) and Fairness of charge (+2.37).\r\n- J.D. Power: 2020 US Customer Service Index (CSI) Study​.",
            "22": "Car owners are just as likely to use Google for an answer than they are to call the dealership with questions.  Very few people call the manufactuer customer service line.",
            "25": "Across mass market brands, there's a lack of communication, or recall of communication about new models, next years line-up and lease renewals. Mazda does a slightly better job.  It's also low among premium owners, but higher tham mass market",
            "Keyword": "Supporting-Data-Body"
        },
        {
            "0": "\"I have owned three Mazdas in my life. It was the first car I owned and I drove it into the ground. It never gave me any problems, it was great.\"\r\n\r\n\"I love Mazdas. My last Mazda I had for 11 years. I really didn't want to get a new car, but we have a new grandson and need more space. I knew straight away I was getting another Mazda. \"",
            "1": "\"I rented a car which introduced me to some new features like seat warmers. Once I had that I new my next car needed to have them!\" ",
            "3": "\"I saw one of the videos about how the designer sculpted the car and it intrigued me because of the aerodynamic aspect of the car. It reminded me that Mazdas are still the only car manufactured in Japan and Japanese cars are great quality.\" ",
            "4": "\"I would be balled over. You don't see this kind of honesty ever. I was rub my eyes in disbelief… It would certainly influence my decision making process - all things equal if Mazda did this it would convince me to go with Mazda.\" (response to seeing the sacraficial prototype highlighting the vehicle designers inspiration for the design)\r\n\r\n\"In this case no - I didn't go out of my way to check to see if they are a socially responsible company but in other things I do.\"",
            "5": "\"I read articles and looked at things online. With Miadas there are some tricks that they don't tell you on most websites... because they are mostly hobby cars you can get these cars that are older models for lower mileage.\"\r\n\r\n\"There are so many options - so many used car dealerships but one thing that was really helpful was the carmax website allows you to look at the carmax shops nationally. Gives me more options, give me ability to search and filter.\"",
            "6": "\"The biggest headache was to get a car during the pandemic. My understanding was it's a pandemic so the dealerships were closed so they would want to sell the cars from their lots. I called around a lot to find someone who would sell of their lot.\"",
            "7": "\"I like to go in with a lot of ammo - I look at car facts and arm myself with information. It stresses me out. I worry if I am getting the best deal and I get serious cases of buyers remorse.\"",
            "8": "\"Test drive I had to do myself - because of the pandemic they just give you the car but I prefer having them in the car because that way I can ask questions.\"\r\n\r\n\"The salesperson really walked me through the process and showed me all the features. Showed me how to do voice activation. Went through the handbook chapter by chapter.\"",
            "9": "\"I had been shopping for this car, for probably like three to six months just looking at all the details and the specs as well as looking at all the rebates and discounts that were being offered.\"",
            "10": "\"My least favourite thing is trying to haggle and see if I can get the better deal. And my most favourite thing is test driving. I enjoy going to a dealer and checking out different models and cars to see what they have. In the pandemic I could do the financial part through the app or online but for test drive, I am still the type of person who wants to visit a dealer.\"",
            "11": "\"I was tired of the standard dealership experience and being treated like an uneducated “female” consumer. I heard about Carvana on TV. The entire experience was amazing and they even made a music video with my car and sent it to me the day before it was delivered. They had gifts placed throughout the car, a roll of quarters for tolls/parking meters, a gas gift card hidden in the door of the gas cap, bottled water etc. they also made good on some issue discovered when the car was delivered and gave me referral cards for friends so they could buy and get $500 a purchase and I got $100 gift card for each card used. It was perfect and seamless from beginning to end.\"",
            "12": "\"As soon as the the rebates came up, I drove down to the first dealership that still had one available in club trim and essentially I did a turn and burn that weekend. I came down to buy the car and I drove it directly at the coastline all the way up Hwy 1 all on the coastline where one side is water and mountain is on the other.\"\r\n\r\n",
            "13": "\"When you are in the car dealership the dealer usually shows you a lot. I was really excited so I go and read the manual. Sometimes you don't know that there is a hidden feature and you get a shock when it does something special.\"\r\n\r\n\"Who ever designed the inside like your stereo is great. Everything is proportionately in reach. It feels very light even though it is an SUV. I could tell this car had been considered.\"",
            "14": "\"I didn't even know that they had an app.\"\r\n\r\n\"I liked it at first and lost my password and that frustrated. If I had to get information I would call direct.\"",
            "15": "\"I was getting emails about congratulations and I kept getting emails from other dealerships.\"\r\n\r\n\"I would love to see some lifestyle based stuff. I have browsed at them but I have not done like a virtual museum - a realtor sent me something interesting with some ideas about things you could do. I saved that email as a matter of fact.\"",
            "16": "\"I am scared to go to the service department because they may charge me even if something is not wrong.\"\r\n\r\n\"We are conservative becuase how the market is going right now. People are being conservative in how thye spend their money and that imapcts me as a hearing aid technician. We are looking to buy a home so we are more  conservative in how we spend our money. We have a Mercedes right now but it is too expesnive so we are looking to transititon to a vehicle that is cheaper to maintain and our Mazda 3 is awesome.\"\r\n\r\n\"Either I will Google or sometimes call a dealer and enquire. Sometimes if they are doing multiple things done they'll give you a deal or a discount.\"",
            "17": "\"I like to go to the shop to see what they are going to do to my car. I don't want to hand over my keys - and I know because of COVID that would be awesome but I still want to go to the shop.\"\r\n\r\n\"I don't feel too comfortable getting people to come pick up my car.\"\r\n\r\n\"I had mixed feelings because then a stranger was going to have to get in the car and I was worried it could be a scam. You never know nowadays..\"",
            "18": "\"I was weary about it but actually I have done it and everything easy and on the computer. So electronically signing things was great. I didn't need to touch anything of theirs.\"",
            "19": "\"When I go and drop my car off I get my loaner car the guy at the dealership is good and since I need transportation for my job he always has given me a car. For them to go out of their way to do that was great.\"\r\n\r\n\"It was nice that they had social distancing and a safe spot for me to wait.\"",
            "22": "\"If something goes wrong I prefer to use my dealer rather than an independent. It is easier to rectify an issue with a big dealership than a small independent shop.\"",
            "23": "\"My heart got broken after that experience and now I realized there are other fish in the water.\"\r\n\r\n\"Since that experience with the local Mazda I don't know if would go back. That bad taste in your mouth doesn't go away.\r\n\r\n\"I would have been happy with an oil change. But now, I am tihnking about buying a honda instead of a cx-9. surely an oil change is cheaper for them\"\r\n\r\n\"It eases your mind because they notify you of recalls so that's why it is good to go to those bigger dealerships.\"",
            "24": "\"We are very convenience driven people. And Main thing right now is cost of maintenance.\"\r\n\r\n\"I am not super loyal to any brand. I like that amazon has one day delivery. It is more about convenience then it is about supporting certain companies.\"\r\n\r\n\"I maintain the car so I have a paper trail showing that I have been keeping my car in good condition\"",
            "25": "Re Nordstrom: \"They treat you better. Macys didn't make me feel like I was important. They make you feel comfortable and they back their product. Even if they customer is wrong I feel like they would still back you.\"\r\n\r\n\"I have a very capitilistic view of businesses - they are doing what they are supposed to do. Everything else is a bonus. Mazda is doing what it is supposed to do which is make cars.\"",
            "Keyword": "Quotes"
        },
        {
            "0": "Help reinforce product value\r\nHelp customers understand the cost of ownership and how much they may have saved compared to competitors.\r\n\r\nIntelligently use data to show brand personality\r\nShare telematics data from previous vehicles where possible to helps customers learn a bit about themselves through their driving behavior (see Spotify Wrapped in bset practices of the Usage touchpoint).",
            "1": "Sponsor car rentals for existing owners\r\nGive existing owners the opportunity to rent better Mazda vehicles while travelling for a reduced rate.\r\n\r\nEngage with a younger audience\r\nBuild brand recognition with a younger audience by engaging with users through alt.Tik Tok or Elite Tik.Tok. Lean into emerging sub-cultures.",
            "4": "Lean into vehicle aesthetic and reliability.\r\nCustomers love Mazda vehicles for their sporty aesthetic and affordable service pricing. \r\n\r\nInfuse the brand message into the experience with in-situ CSR information\r\nSupport consumers desires to be more mindful in where they shop by showing information about factory locations, how staff are treated, ultra-transparent pricing breakdowns and/or source of materials [refer to Everlane Clothing Pricing Transparency best practice example].",
            "5": "Build on the nostalgia of car shopping\r\nFor many, car advice is best taken from a friend or family member who knows more about cars then they do and for some of these individuals, the experience of going with a family member to a dealership is very nostalgic. How might we cater to those for whom going to the dealership is not a chore, but something to be treasured?\r\n\r\nHelp customers move from exploratory to evaluative mindsets when in the information gathering stage.\r\nIf a user is prompted or encouraged to have an emotional response to something like feeling is believing they should be afforded the ability to engage in the challenge laid out (E.g. feeling is believing statement on Skyactive webpage).\r\n\r\nPrepare for s sharp rise in CPO/used sales\r\nCustomers will increasingly look to evaluate the pros and cons of buying new and used vehicles. Recent socio-political events have made customers more financially conservative and as a result CPO and used car sales are on the rise. Although providing little direct financial benefit in the short term, the long term benefits of this could be significant.",
            "6": "Put customers in control\r\nCustomers are having to do the hard work by following up with individual dealers to get prices and deals. Provide a platform for them to post vehicle interst and let dealers chase the customer. \r\n\r\nEncourage customers to get pre-approved for a loan\r\nMake sure customers are not only given the option but actively encouraged to get pre-approved for a loan before the begin conversations with a salesperson.",
            "8": "Get salespeople in the car with customers (digitally)\r\nThink of alternative ways salespeople can safely engage with customers test driving vehicles as many of the features 'come to life' while on the test drive. \r\n\r\nPro-active service recovery\r\nDealerships are one of the most volatile moments in the journey as they can swing potential customers sentiment strong one way of the other. Need to resolve post dealership survey challenges.\r\n\r\nTest drive stations free of any dealers\r\nProvide 'do-it-yourself' test drive options so customers can explore vehicles without the pressure of a sales associate nearby.",
            "9": "Allow customers to provide additional information when booking appointments online so their in-person experience can be more tailored to their needs, quicker and smoother.\r\n\r\nSend thank you text following dealership visit so customers stay engaged. They are looking for sales staff who go above and beyond to put trust into.\r\n",
            "10": "Lean into Roadster\r\nAlready underway, the digital retailing initiative using Roadster will provide IAs the flexibility to digitally engage in the parts of the experience they would prefer to be remote.\r\n\r\nCreate cross device experiences to reduce contact when in person meetings occur\r\nAllow customers to engage completely through their own devices. Create a shared experience that reduces contact between staff and customers.",
            "11": "Always hand over a key\r\nEven if the key may not be to the car it could unlock of world of luxury that only Mazda owners can access. Providing something physical other than financial papers could become a uniquely Mazda signature experience that links to a digital experience provided through the website or application.",
            "12": "Give customers direction\r\nProvide a list of nearby places to drive to that they can explore after picking up the car or provide something like a national park pass so they can continue to get out of town and enjoy the freedom of having their car.\r\n\r\nPartner with third parties\r\nFind opportunities to integrate with third parties to streamline the purchase process.\r\n",
            "13": "Bring Takumi to life\r\nTell the story of the car. How it came to be and who are the people and the experiences who inspired it (see Takumi prototype in full research report). \r\n\r\n\"Stories are great to get people to connect on a human level. It would make me feel that they were thinking more than the profit motive - that they knew the why. They could understand and articulate it.\" \r\n\r\nUse tools and data you already own to more deeply connect with customers\r\nUse telematics data to trigger comms and reminders to customers to engage with and use certain features.\r\n\r\nMake it easy to learn on the go\r\nCustomers are foten using the vehicle (driving) when they have a questions about how something works. Consider using a voice assistant to help customers navigate the manual and deepen their understanding of the vehicle.",
            "14": "Reach out to help, even when nothing is wrong\r\nPro-actively reach out to customers asking if there is anything you can do to help.\r\n\r\nProvide incentives to encourage customers to channel switch\r\nUsing the app provides a better experience and an additional channel of communication. Encourage customers to onboard so they can be given the best possible experience.",
            "15": "Send lifestyle based communications\r\nPeople are looking for things to do. With COVID imapcting the way we live our lives customers value anything that is respectful and understanding of the situation we are in but seeks to help and inspire. When we tested the concept one customer loved it so much they asked how they subscribe and if they could specificy the things/topics they were interested in and area they live in.\r\n\r\n\"I would absolutely be interested in things like that.\" \r\n\r\nhttps://wppcloud.sharepoint.com/:i:/s/wt-MAZDA-NorthAmerica/EWWBATutZBxPui3JQCjFMIUBQ_W1LoGe1oyGLXc4nSs2QA?e=fI55TM",
            "16": "Communicate via social media\r\nUse targetted, personalized advertisements to speak direcetly to customers via social media and allow them to book in appointsments directly through the platform of choice. \r\n\r\nCreate a dealership marketplace\r\nAllow customers to post a job online and let different dealerships make offers depening on what they are willing to charge [alternatively have a standard charge for different services across the board].\r\n\r\nPut customers minds at ease\r\nDevelop campaigns or initiatives thatencourage price sensitive customers to service their vehicles at the Mazda service center.",
            "17": "Ease of scheduling is now Mazda's largest weighted-gap opportunity to Top 3 brands\r\nDriven largely by ongoing challenges with Days Waited for Appointment, suggesting larger concerns with service capacity.\r\n\r\nOvercome trust issues around service pick up and delivery\r\nCustomers have indicated the desire to use this but show low intent to engage. There is a need to provide additional confidence throughout the sub-journey to support users and encourage them to engage.\r\n\r\nOvercome trust issues to provide a premium experience that IAs want\r\nIndependant Achievers show high levels of interest in the pick up and delivery service. Overcome trust issues to provide a uniquely Mazda experience that caters for a more premium customer.",
            "18": "Allow customers to do everything on their own device\r\nAllow customers to only use their devices when checking in and engaging with the service center rather than having to touch communal surfaces.",
            "20": "Work with service centers to provide unexpected benefits \r\nSurprise and delight customers will bonuses and benefits they never expected to build trust and increase service retention.",
            "23": "Develop a strategy for service recovery and empower CEC staff to surprise and delight customers when service failures occur.\r\nIn response to asking what a OEM can do to right a wrong:\r\nMake sure their dealerships don't treat you like you are just here to buy another car, They need to deal with their independence issues. The first impression I get from Mazda was the person who sold me the car.\r\n\r\n\"When you call corporate make sure you make them feel like a good customer. Since that experience with the local Mazda I don't know if would go back. That bad taste in your mouth doesn't go away.\"",
            "24": "Invest in reliability, transparency, trust and understanding",
            "Keyword": "Opportunities"
        },
        {
            "0": "Peak-End Rule",
            "3": "Authority Bias",
            "4": "Desire for self-transcendence",
            "5": "Zero-risk Bias",
            "8": "Peak-End Rule",
            "10": "Peak-end Rule",
            "11": "The Power of Now",
            "12": "The Power of Now",
            "13": "The IKEA effect",
            "16": "Loss Aversion",
            "20": "Power of Free",
            "23": "The Service Recover Paradox",
            "24": "Receny Effect",
            "25": "The power of showing up",
            "Keyword": "Behavioral-Theory-Header"
        },
        {
            "0": "The Peak–End Rule is a psychological heuristic in which people judge an experience largely based on how they felt at its peak and at its end, rather than based on the total sum or average of every moment of the experience. The effect occurs regardless of whether the experience is pleasant or unpleasant. \r\n\r\nHow might we expose the peak moments of car ownership to customers more regularly and ensure the last memory they have of their car is a positive one?",
            "3": "Authority Bias is the tendency to attribute greater accuracy to the opinion of an authority figure and be more influenced by that opinion.",
            "4": "in Maslows heirarchy of needs Self-actualisation is at the very top. In recent years organisations have come to relaize that customers (specifically millenials) will put their money where their mouth is and support brands that have a positive social impact as it allows them to help others or society more broadly.",
            "5": "Zero-risk Bias is a tendency to prefer the complete elimination of a risk in a sub-part even when alternative options produce a greater overall reduction in risk.",
            "8": "The Peak–End Rule is a psychological heuristic in which people judge an experience largely based on how they felt at its peak and at its end, rather than based on the total sum or average of every moment of the experience. The effect occurs regardless of whether the experience is pleasant or unpleasant. \r\n\r\nHow might we expose the peak moments of car ownership to customers more regularly and ensure the last memory they have of their car is a positive one?",
            "10": "The peak–end Rule is a psychological heuristic in which people judge an experience largely based on how they felt at its peak and at its end, rather than based on the total sum or average of every moment of the experience. The effect occurs regardless of whether the experience is pleasant or unpleasant.",
            "11": "Power of now describes the fact that we tend to want things now rather than later. Humans are wired to live in the present – our evolutionary survival hinged on our ability to deal with the problems of the here and now rather than our ability to plan for the future. This explains why people often find it a challenge to save for their future. “Power of now” also explains the success of instant downloads or 24-hour delivery versus having to wait to get a product.\r\n- Google: Decoding Decisions: Making sense of the messy middle, 2020.",
            "12": "Power of now describes the fact that we tend to want things now rather than later. Humans are wired to live in the present – our evolutionary survival hinged on our ability to deal with the problems of the here and now rather than our ability to plan for the future. This explains why people often find it a challenge to save for their future. “Power of now” also explains the success of instant downloads or 24-hour delivery versus having to wait to get a product.\r\n- Google: Decoding Decisions: Making sense of the messy middle, 2020.",
            "13": "The IKEA effect is a cognitive bias in which consumers place a disproportionately high value on products they partially created. The name refers to Swedish manufacturer and furniture retailer IKEA, which sells many items of furniture that require assembly.",
            "16": "Loss aversion is the tendency to prefer avoiding losses to acquiring equivalent gains. The principle is prominent in the domain of economics. What distinguishes loss aversion from risk aversion is that the utility of a monetary payoff depends on what was previously experienced or was expected to happen.",
            "20": "Power of free describes the fact that there is something special about the price of zero. The demand for a product or service is significantly greater at a price of exactly zero compared to a price even slightly greater than zero. The power of free can be thought of as an emotional hot button – a source of irrational excitement that can be critical in persuading a consumer to make a purchase decision.",
            "23": "If treated well it’s a proven fact that customers can often be more loyal to your business after they have experienced a service failure, than if it had never happened in the first place.\r\n\r\n‘If there is a positive disconfirmation, that is, if perceptions of service recovery performance are greater than expectations, a paradox might emerge (secondary satisfaction becomes greater than prefailure satisfaction).\r\nhttps://www.customerthermometer.com/customer-retention-ideas/the-service-recovery-paradox/",
            "24": "Recent events are easier to remember, and can be\r\nweighed more heavily than past events or potential\r\nfuture events.",
            "25": "Simply giving shoppers the option to choose their second choice brand was enough to entice 30% away from their initial choice.",
            "Keyword": "Behavioral-Theory-Body"
        },
        {
            "1": "Airlines upgrading customers\r\nAirlines will often upgrade customers to higher classes so they are able to experience something they would not otherwise pay for. This increases the likelihood of them paying for an upgrade the next time they travel.",
            "3": "Honda R parallel storyline \r\nFor the release of the Civic Type R Honda creat an Interative video called 'The Other Side' that let users explore the emotional and rational 'sides' of the car.\r\nhttps://www.youtube.com/watch?time_continue=27&v=FU5CLg2LAmg&feature=emb_title\r\n\r\nMazda 100 - Designing a car with clay\r\nhttps://www.youtube.com/watch?v=Y-bIwmTD-mI",
            "4": "Everlane (Pricing transparency)\r\nToms shoes (Social impact)\r\nPatagonia (Environmental impact)\r\nNudie Jeans (Circular Economy)\r\nLemonade Insurance (Fair Business Model)",
            "5": "Nudie return policy\r\nBurton lifetime waranty\r\nPatagonia lifetime waranty\r\nFord Motor Co. - one year potection plan for customers who lose their job.",
            "6": "Hyundai Click-to-Buy\r\nGM Test Drive from Anywhere\r\nFacebook marketplace",
            "8": "Infinity Now: Infinity takes virtual showrooms to new heights with video conferencing.\r\n\r\nLexus: Find your unbeaten path. https://lexus-ux-app.com/",
            "11": "Porsche released an app that allowed customers to set up and learn about their car while they waited for it to be delivered. Providing the ability to set seat heights, set home address and link music listening software meant by the time the car was delivered it felt like theirs and they knew exactly how to use it.",
            "12": "Airlines building insurance into their purchase process\r\nAirlines and hotels building in additional services into the post-purchase experience that relate to the trip you are booking.",
            "13": "M. Chapoutier - A wine producer tells a story on their label about their son who could never select their own wine so they started putting Braille on their bottles. They were the first ever. ",
            "14": "Spotify wrapped\r\nhttps://newsroom.spotify.com/2019-12-05/spotify-wrapped-2019-reveals-your-streaming-trends-from-2010-to-now/",
            "15": "Airline magazines / horizontal movement into travel related topics.\r\n\r\nKia 'Let's Road Trip' Campaign",
            "17": "Mazda: Essential Car Care Program\r\nUber: Ubers provide a range of features directed specifically at overcoming trust barriers (forced driver ratings, ride tracking, direct emergency service button)\r\nAirBnb: Airbnb hired professional photographers, mandated profile description lengths and content all to encourage users to adopt their platform (https://www.ted.com/talks/joe_gebbia_how_airbnb_designs_for_trust?language=en).\r\n",
            "18": "Cuculi: Allows restaurant patrons to view the menu, order and pay all via their mobile device: https://cuculi.com/",
            "19": "CitizenM hotel: Unique approach to hospitality (https://www.youtube.com/watch?v=ru0uR2w-euA)",
            "20": "Uber: When uber started they faced similar trust issues. Overcommunicate, customer reviews, full transparency and positive word of mouth all helped customers feel confident they would be safe getting into someone else's car.",
            "23": "A ski resort that bought people stuck on a broken chair lift for an hour in the cold a hot drink and gave them free ski passes.\r\n\r\nA homewares company who included a free toy car in a furniture delivery for a little boy who had to wait for his new bed two weeks longer than promised.",
            "24": "Apple and their operating system creating a network/ecosystem of value\r\nReferal bonuses, loyalty bonuses\r\nLiberty Mutual 'you loved brad' twitter campaign. December 2016",
            "Keyword": "Best-Practices"
        },
        {
            "0": "Car owners would prefer to be brand loyal",
            "1": "People are still not comfortable with public transport because of COVID-19",
            "4": "Americans feel a deeper bond with purpose-driven companies",
            "5": "Between the twin poles of trigger and\r\npurchase sits the messy middle",
            "6": "Customer adoption of online retailing for auto has accellerated, fueled by expectations and disruptions.",
            "7": "Consumers pit dealerships against each other",
            "8": "OEMS and dealerships that leaned in to online retailing saw benefits.",
            "9": "Limited inventories and fewer incentives continue to hold back sales in the US. \r\n- Counterpoint: Weekly Update: COVID-19 Impact On Global Automotive Industry",
            "11": "During COVID cars become a private oasis and customers wanted it right away",
            "12": "COVID accelerated vehicle delivery expectations\r\n",
            "14": "The MyMazda app needs improvement",
            "16": "Invest in vehicle reliability, affordability and maintenance cost to retain customers in a conservative market",
            "17": "Plummeting car sales will have longer term effects on auto maintenance",
            "23": "\"It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently\" - Warren Buffet",
            "24": "Consumers would prefer to be\r\nbrand loyal",
            "25": "Build relevance where it matters",
            "Keyword": "Third-Party1-Header"
        },
        {
            "0": "More than 50% of consumers said they would prefer to purchase a vehicle from the same auto brand.\r\n- Mintel: Creating Loyalty In Automotive. January 2020.",
            "1": "57% of customers are not comfortable taking public transport.\r\n- Mintel: Car Purchasing Process: Incl Impact Of COVID-19 US, July 2020.",
            "4": "79% Say they would be more loyal to a purpose-driven company\r\n77% Say they feel a stronger emotional connection to purpose-driven companies \r\n73% Say they would be likely to defend a purpose-driven company is people spoke badly of it\r\n\r\n- Cone/Porter Novelli Purpose Study: How to Build Deeper Bonds, Amplify Your Message and Expand Your Consumer Base, 2018.",
            "5": "Customers loop through mental states of exploration and evaluation. Googles 'decoding decisions' research explains how consumers make decisions online..\r\n- Google: Decoding Decisions: Making sense of the messy middle, 2020.\r\n\r\nhttps://wppcloud.sharepoint.com/:b:/s/wt-MAZDA-NorthAmerica/Ee3NYT8jJytIt2oBPHP64zUBeo0kK-rSEDuuvUQq9bANTw?e=K0KpCq",
            "6": "In 2018 1% of new vehicles were sold online. In the 1st half of 2020 about 10% of new vehicles were sold online.\r\n\r\nIn 2005 customers visited and average of 5 dealerships per purchase. In 2020 93% of auto buyers to their research online and visit on avergae 1.5 dealerships per purchase.\r\n- Google: Driving Digital Transformation through Online Retailing, 2020.",
            "7": "Competitive pricing trumps vehicle incentives when it comes to pre-purchase research topics. Consumers are always looking for a deal but will now plan to pit dealerships against each other to see who will provide the best price. Dealerships will in turn need to ensure that they’re listing all stackable and applicable incentives to their vehicle detail pages.\r\n- Mintel: Car Purchasing Process: Incl Impact Of COVID-19 US, July 2020.",
            "8": "For Infiniti: \r\n60% of dealers are derlivering sanitized vehicles for at home test-drives. \r\n70% of customers want the offering to continue post-pandemic. \r\n- Google: Driving Digital Transformation through Online Retailing, 2020.",
            "11": "Companies with inventory issues have struggled during COVID as customers want vehicles immediately.",
            "12": "Before the pandemic only 7% of vehicles were delivered to customers home from Paragon Honda.\r\nIn may 2020 100% of the 775 vehicles sold were delivered to customers homes.\r\n- Google: Driving Digital Transformation through Online Retailing, 2020.",
            "14": "The App has a score of 2.5/5 and 2.8/5 on the Apple and google app stores respectively.",
            "16": "OEMs should be advertising national campaigns that focus on service-related specials just as much as they focus on vehicle related incentives. Consumers are heavily driven by Value, one of Mintel’s Consumer Trend Drivers, and more specifically 70% of US consumers said that they try to stick to a budget as closely as possible. For automakers, this consumer sentiment means that they should be prioritizing service specials just as much as they prioritize vehicle incentives. OEMs should be advertising national campaigns that focus on service-related specials just as much as they focus on vehicle related incentives.",
            "17": " A number of consumers can be expected to hold off on new vehicle purchases in the immediate future. These purchase delays will benefit the auto maintenance industry as consumers will prioritize repairs on their current vehicle. While the COVID-19 pandemic is vastly different from the 2008 Recession, there are a few exceptions where consumer behaviors will parallel, one of which being vehicle maintenance. During times of economic distress, consumers are more likely to invest in repairing their current vehicle rather than invest in a newer model. While the pandemic will be a boon to the auto maintenance industry, OEMs still have an opportunity to capitalize on the current environment. OEMs have been heavily prioritizing new vehicle incentives since the start of the pandemic. And while it’s great to see such record breaking incentives being offered – it ignores the consumers who can’t afford a new vehicle and are scrambling to figure out how to afford necessary repairs to their current vehicle.\r\n- Mintel: Car Purchasing Process: Incl Impact Of COVID-19 US, July 2020.",
            "24": "More than 50% of consumers said they\r\nwould prefer to purchase a vehicle from the same auto brand. While loyalty has strong emotional sentiments, this sentiment from consumers most likely comes from a mindset of convenience rather than a strong desire to form an emotional connection to an automaker.\r\n\r\nBy having a desire to purchase from the same auto brand, consumers likely are looking for a way to simplify the car purchasing process and reduce the amount of research necessary. They would have a baseline understanding of what to expect from a familiar automaker rather than having to spend lots of time researching vehicle types, specifications and incentive offerings\r\n\r\n55% of customers say they'd prefer to purchase a car from the same auto brand.\r\n\r\n75% of customers say that 'low maintenance earns my loyalty to autp brands'",
            "25": "Simply giving the shopper the option to choose their second choice brand was enough to entice 30% away from their initial choices. [Google decoding decisions]",
            "Keyword": "Third-Party1-Body"
        },
        {
            "5": "We are seeing deals that weren't even around during the 2008 great depression",
            "8": "Auto buyers are driving the change toward a customer-led, frictionless experience",
            "23": "The ownership experience is a key factor in repeat purchase",
            "Keyword": "Third-Party2-Header"
        },
        {
            "5": "OEMs have offered 0% APR on an 84-month loan, deferred payment plans – Ford Motor Co. has even offered customers a one year protection plan which would allow new customers the opportunity to return their car in the event of a job loss up to one year after their purchase date. The offerings are quite remarkable especially considering such offerings weren’t provided during the 2008 Great Recession.\r\n- Mintel: Car Purchasing Process: Incl Impact Of COVID-19 US, July 2020.",
            "8": "73% of customers are comfortable negotiating purchase, lease or financing terms completely online or with a mix of online/offline. \r\n- Google: Driving Digital Transformation through Online Retailing, 2020.",
            "23": "35% of customers (the most out of any category) say that poor vehicle experience is the top rated thing that would encourage them to purchase a different auto brand from their current vehicle.",
            "Keyword": "Third-Party2-Body"
        },
        {
            "5": "During this stage, Mazda and overall mass market owners are most satisfied with visiting review sites and talking to others who recently purchased/leased vehicle.\r\n\r\nPremium owners are most satisfied with visiting manufacturer websites and visiting review sites.",
            "6": "Request a Brochure: Prefer E-Mail or Direct Mail\r\n\r\nRequest to be contacted by dealer: Prefer E-Mail or Online/Through website\r\n\r\nSpeak with sales associate before visit: Prefer Email or  Phone call\r\n\r\nPremium owners and Mazda owners are more likely than mass market owners to watch videos on the make/model and reviews on YouTube. Premium owners are especially satisfied with this experience",
            "7": "IAs are the most satisfied with 3rd party websites during the information gathering phase.",
            "8": "In person vs. delivery test drives\r\nMost didn't have their vehicle delivered to their home (10% premium, 4% mass market), but the majority find the idea of home delivery to be appealing (77% Premium, 65% Mass Market owners find it very/somewhat appealing).",
            "9": "Ias and Premium customers like choosing vehicle options but every tool is the same\r\nThe build and price tool is being overserved in the market with every manufacturer offering the opportunity to do so in a like-for-like experience. How might we use other channels when providing this experience?",
            "14": "Receive thank you note for visiting dealership: Prefer Email and Direct Mail",
            "16": "Email and Text message is preferred by all.\r\nPremium, IAs and those under 50 also prefer Mobile app push notifications.",
            "19": "Receive progress update during service: Prefer Text message, Email, In-person, Phone call. Premium,  Ias and those under 50 also prefer Mobile app (push, messagine, feature)",
            "23": "Receive notifaction about parts/vehicle recall: Prefer Email, Direct Mail, Text message. IA's also prefer Mobile App (push, messagine, feature)",
            "25": "Receive info about new model/next year's line-up or early lease renewal: Prefer Email and Direct Mail. Premiums owners, Ias and those under 50 also prefer Mobile app",
            "Keyword": "Channel-Preference"
        }
    ];


export function getJsonDataString() {
    return jsonData;
}